version: "3.7"
services:  
  dep_1:
    build: 
        args: 
          user: app
          uid: 1000
        context: .
        dockerfile: ./Dockerfile
    image: dep_1:latest
    container_name: app_enesis
    working_dir: /var/www

    networks:
        - dep_1
    volumes:
        - ./etc/php/www.conf:/etc/php-fpm.d/www.conf
        - ./etc/supervisor/supervisord.conf:/etc/supervisord.conf
        - ./etc/supervisor/conf.d:/etc/supervisor/conf.d
        - ./etc/nginx/Config/nginx.conf:/etc/nginx/nginx.conf
        - ./etc/nginx/serverblock:/etc/nginx/serverblock
        - ./../www/project/:/var/www/project
        - ./../www_view/:/var/www/project_view
    restart: always
  dep_socket:
      build: 
          args: 
            user: app
            uid: 1000
          context: .
          dockerfile: ./Dockerfile
      image: dep_socket:latest
      container_name: app_gesang
      working_dir: /var/www
      ports: 
          - 91:91
          - 3000:3000
          - 9191:9191 
          - 9292:9292 
      networks:
          - dep_1
      volumes:
          - ./etc/php/www.conf:/etc/php-fpm.d/www.conf
          - ./etc/supervisor/supervisord.conf:/etc/supervisord.conf
          - ./etc/supervisor/conf.d:/etc/supervisor/conf.d
          - ./etc/nginx/Config/nginx.conf:/etc/nginx/nginx.conf
          - ./etc/nginx/serverblock:/etc/nginx/serverblock
          - ./../www_socket:/home/app/www_socket
          - ./../www_gesang:/home/app/www_gesang
          - ./../www_brain:/home/app/www_brain
      restart: always
  db_dep_1:
    image: mariadb:latest
    container_name: db_enesis
    environment:
      MYSQL_DATABASE: enesis_db
      MYSQL_ROOT_PASSWORD: 2134
      MYSQL_PASSWORD: 2134
      MYSQL_USER: enesis
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
        - ./etc/databases:/var/lib/mysql/
    restart: always
    ports: 
        - 23751:3306
    networks:
        - dep_1
networks:
  dep_1:
    driver: bridge
